# fly.toml app configuration file generated for fetch-dog-app2 on 2023-10-06T23:47:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fetch-dog-app2"
primary_region = "lax"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
